### PR TITLE
Redoinspect2 anthony

### PR DESCRIPTION
**Pull request by Oddant1**
This is a branch off of #507. It cleans up `get_formats_helper` and adds relevant tests. The copyright headers will currently explode in this PR and cause Travis failure.

### CODE REVIEW

**Comment by Oddant1** [comment]
The test failures on Travis are due to issues with Travis not the code. This code SHOULD work.

**Comment by thermokarst** [comment]
[These issues](https://travis-ci.org/qiime2/qiime2/builds/638548750#L1257-L1371) have been addressed in #515 - please update this branch to resolve.

Are you anticipating the [errors outlined here](https://travis-ci.org/qiime2/qiime2/builds/638548750#L1376-L1433), too?

**Comment by Oddant1** [comment]
Closed and reopened to prompt Travis

**Comment by thermokarst** [comment]
> Closed and reopened to prompt Travis

Don't forget to merge in the updates that [I mentioned above](https://github.com/qiime2/qiime2/pull/516#issuecomment-576498426), otherwise q2lint will continue to fail on travis.

**Comment by Oddant1** [comment]
https://github.com/qiime2/qiime2/pull/516/commits/d05945728452a0026f4512f25ba83c7e1631241b did fix the linting errors. So it should be running the latest version of the code?

**Comment by thermokarst** [comment]
> So it should be running the latest version of the code?

Not exactly, since you have created an all-new commit, rather than merging. Now you are dealing with diverging state. Not a big deal, but just something you should be aware of (and also why I suggested _merging_ the changes in, versus manually recreating in our IRL discussion).

**Comment by ebolyen** [comment]
supplanted by #522

**Pull request closed without merging**
