### PR TITLE
ENH: Add Result.export_data to sdk

### PR DESCRIPTION
**Pull request by jakereps**
Adds `Result.export_data` to `qiime.sdk` for exporting the data directories to the user's filesystem.

### CODE REVIEW

**Comment by thermokarst** [comment]
@jakereps, after discussing with @gregcaporaso, @ebolyen, and @jairideout the lack of transformers to support the `format` argument , we think for now we should just drop that functionality (at least until we add in some of the missing transformers). How about something like this:

```python
def export_data(self, output_dir):
    from shutil import copytree
    copytree(str(self._archiver.data_dir), output_dir)
```

**Comment by jakereps** [comment]
Sounds good, yeah it took hacking another transformer into `q2_types` to even test if it was working. Any preference on using the already imported `copy_tree`  from [here](https://github.com/qiime2/qiime2/pull/172/files#diff-86a19f23a3f1b6170b33fcc238c64704L247) over importing `shutil` as well?

**Comment by thermokarst** [comment]
No preference here --- if it works then it is one less import!

**Comment by jakereps** [comment]
Thanks @thermokarst and @jairideout! Should be good after tests 👍 !

**Pull request merged**
