### PR TITLE
Add get transformers

### PR DESCRIPTION
**Pull request by Oddant1**

### CODE REVIEW

**Comment by thermokarst** [comment]
Hey @Oddant1, I just updated the base branch from `master` to `import_wizard`. Also, @ebolyen and I had a chance to discuss this SDK method today, the plan is to punt it for now, you won't need it from the _Import Wizard_ (although it'll be really helpful in the work immediately to follow the wizard project).

**Comment by Oddant1** [comment]
Close and reopen because Travis stalled on this a while back

**Comment by lizgehret** [comment]
Hey @Oddant1 is this still current, or should we close it out?

**Comment by Oddant1** [comment]
Yeah, @lizgehret I'm pretty sure this can go. Even the branch it was being merged into is outdated at this point. If we ever take another crack at this idea we're gonna need to start over.

**Pull request closed without merging**
