### PR TITLE
ENH: support for QIIME 1 feature metadata files in qiime.Metadata

### PR DESCRIPTION
**Pull request by jairideout**
qiime.Metadata and qiime.MetadataCategory reprs use underlying DataFrame repr instead of JSON. Added HTML repr to qiime.Metadata.

Pair-programmed with @jakereps.

### CODE REVIEW

**Comment by ebolyen** [comment]
I like this, just need to test with `studio`/`q2cli` in case they have janky uses of the `repr`

**Comment by jairideout** [comment]
We tested the studio and q2cli using the emperor plugin which accepts metadata as input. Things appear to be non-janky!

**Comment by ebolyen** [comment]
Thanks @jairideout and @jakereps!

**Comment by ElDeveloper** [comment]
:tada:

**Pull request merged**
