### PR TITLE
nest everything in folder in supplement zip

### PR DESCRIPTION
**Pull request by colinvwood**
addresses #731

### CODE REVIEW

**Review by gregcaporaso — CHANGES_REQUESTED** [review]
@colinvwood, this looks good but I notice there are no replay_supplement tests to update here. Would you add a test that calling replay_supplement creates the expected zip file, and then that unzipping that results in the expected directory structure? I think that will be our first replay_supplement test.

**Comment by colinvwood** [comment]
@gregcaporaso the replay supplement tests are in q2cli because qiime2 can't depend on q2cli

**Comment by colinvwood** [comment]
@gregcaporaso tests updated in qiime2/q2cli#325

**Review by gregcaporaso — APPROVED** [review]
Looks good! I tested locally and everything is working as expected now.

**Pull request merged**
