### PR TITLE
API: adds `qiime.util.get_filepath_from_package`

### PR DESCRIPTION
**Pull request by lizgehret**
Reverts qiime2/qiime2#799

### CODE REVIEW

**Comment by lizgehret** [comment]
@gregcaporaso and I discussed offline about updating the implementation of this helper within `TestPluginBase` to catch the `FileNotFoundError` and proceed. This allows the associated unit tests in q2-types to still run through the validation step without failing on FileNotFound.

**Comment by gregcaporaso** [comment]
After some discussion we decided to update the test to align with this API change. Our perspective is that raising the error is how the function _should_ work, and it's highly unlikely that tests are expecting the requested file not to exist outside of the framework or q2-types, so we're going to treat this as a bug fix.

**Comment by gregcaporaso** [comment]
Depends on merge of https://github.com/qiime2/q2-types/pull/343 for integration tests to pass.

**Comment by lizgehret** [comment]
Tests all passed on https://github.com/qiime2/q2-types/pull/343 and it's been merged into dev. I'll go ahead and merge this as well, thanks @gregcaporaso!

**Comment by gregcaporaso** [comment]
Thanks @lizgehret!

**Pull request merged**
